import { describe, expect, it } from "vitest";
import type { Rule, RuledocConfig } from "../types.js";
import { DEFAULT_CONFIG } from "../types.js";
import { generateContext } from "./context.js";

function makeRule(overrides: Partial<Rule> = {}): Rule {
  return {
    scope: "billing",
    subscope: "_general",
    fullScope: "billing",
    severity: "info",
    ticket: "",
    description: "test rule",
    file: "test.ts",
    line: 1,
    codeContext: "",
    ...overrides,
  };
}

function makeConfig(overrides: Partial<RuledocConfig> = {}): RuledocConfig {
  return { ...DEFAULT_CONFIG, ...overrides };
}

describe("generateContext", () => {
  it("produces header with rule count, scope count, and date", () => {
    const rules = [makeRule(), makeRule({ scope: "auth", fullScope: "auth.session" })];
    const output = generateContext(rules, makeConfig());
    const lines = output.split("\n");

    expect(lines[0]).toBe("# Business Rules (auto-generated by ruledoc — do not edit)");
    expect(lines[1]).toMatch(/^# 2 rules · 2 scopes · Generated \d{4}-\d{2}-\d{2}$/);
  });

  it("sorts by severity descending then fullScope alphabetically", () => {
    const rules = [
      makeRule({ fullScope: "billing.plans", severity: "info" }),
      makeRule({ fullScope: "auth.session", severity: "critical" }),
      makeRule({ fullScope: "auth.password", severity: "critical" }),
      makeRule({ fullScope: "notify.email", severity: "warning" }),
    ];
    const output = generateContext(rules, makeConfig());
    const ruleLines = output.split("\n").filter((l) => l.startsWith("["));

    expect(ruleLines[0]).toContain("[critical] auth.password:");
    expect(ruleLines[1]).toContain("[critical] auth.session:");
    expect(ruleLines[2]).toContain("[warning] notify.email:");
    expect(ruleLines[3]).toContain("[info] billing.plans:");
  });

  it("filters by context.severities", () => {
    const rules = [
      makeRule({ severity: "info", fullScope: "a" }),
      makeRule({ severity: "critical", fullScope: "b" }),
      makeRule({ severity: "warning", fullScope: "c" }),
    ];
    const config = makeConfig({ context: { severities: ["critical", "warning"] } });
    const output = generateContext(rules, config);
    const ruleLines = output.split("\n").filter((l) => l.startsWith("["));

    expect(ruleLines).toHaveLength(2);
    expect(ruleLines[0]).toContain("[critical]");
    expect(ruleLines[1]).toContain("[warning]");
  });

  it("truncates to maxRules", () => {
    const rules = Array.from({ length: 10 }, (_, i) =>
      makeRule({ fullScope: `scope${i}`, description: `rule ${i}` }),
    );
    const config = makeConfig({ context: { maxRules: 3 } });
    const output = generateContext(rules, config);
    const ruleLines = output.split("\n").filter((l) => l.startsWith("["));

    expect(ruleLines).toHaveLength(3);
  });

  it("truncates long descriptions to keep lines ≤ 120 chars", () => {
    const longDesc = "A".repeat(200);
    const rules = [makeRule({ description: longDesc })];
    const output = generateContext(rules, makeConfig());
    const ruleLines = output.split("\n").filter((l) => l.startsWith("["));

    expect(ruleLines[0].length).toBeLessThanOrEqual(120);
    expect(ruleLines[0]).toContain("…");
  });

  it("produces header only for empty rules", () => {
    const output = generateContext([], makeConfig());
    const lines = output.trimEnd().split("\n");

    expect(lines).toHaveLength(2);
    expect(lines[0]).toContain("Business Rules");
    expect(lines[1]).toContain("0 rules · 0 scopes");
  });

  it("ends with trailing newline", () => {
    const output = generateContext([], makeConfig());
    expect(output.endsWith("\n")).toBe(true);
  });

  it("includes file and line in parentheses", () => {
    const rules = [makeRule({ file: "src/billing.ts", line: 42 })];
    const output = generateContext(rules, makeConfig());
    expect(output).toContain("(src/billing.ts:42)");
  });

  it("sorts unknown severities after known ones", () => {
    const rules = [
      makeRule({ fullScope: "a", severity: "info" }),
      makeRule({ fullScope: "b", severity: "custom" }),
      makeRule({ fullScope: "c", severity: "other" }),
    ];
    const output = generateContext(rules, makeConfig());
    const ruleLines = output.split("\n").filter((l) => l.startsWith("["));

    expect(ruleLines[0]).toContain("[custom] b:");
    expect(ruleLines[1]).toContain("[other] c:");
    expect(ruleLines[2]).toContain("[info] a:");
  });
});
