import type { Rule, RuledocConfig } from "../types.js";

// ---------------------------------------------------------------------------
// Context format — LLM-optimized flat text output
// ---------------------------------------------------------------------------

export function generateContext(rules: Rule[], config: RuledocConfig): string {
  const ctx = config.context;

  // Filter by severities if configured
  let filtered = rules;
  if (ctx?.severities && ctx.severities.length > 0) {
    const allowed = new Set(ctx.severities);
    filtered = filtered.filter((r) => allowed.has(r.severity));
  }

  // Sort: severity priority descending (critical first), then fullScope alphabetically
  const sevOrder = [...config.severities].reverse();
  const sevIndex = new Map(sevOrder.map((s, i) => [s, i]));

  filtered = [...filtered].sort((a, b) => {
    const sa = sevIndex.get(a.severity) ?? -1;
    const sb = sevIndex.get(b.severity) ?? -1;
    if (sa !== sb) return sa - sb;
    return a.fullScope.localeCompare(b.fullScope);
  });

  // Truncate to maxRules
  if (ctx?.maxRules && ctx.maxRules > 0) {
    filtered = filtered.slice(0, ctx.maxRules);
  }

  // Header
  const scopes = new Set(filtered.map((r) => r.scope));
  const date = new Date().toISOString().slice(0, 10);
  const lines: string[] = [
    `# Business Rules (auto-generated by ruledoc — do not edit)`,
    `# ${filtered.length} rules · ${scopes.size} scopes · Generated ${date}`,
  ];

  // One rule per line
  for (const r of filtered) {
    const prefix = `[${r.severity}] ${r.fullScope}: `;
    const suffix = ` (${r.file}:${r.line})`;
    const maxDesc = 120 - prefix.length - suffix.length;

    let desc = r.description;
    if (prefix.length + desc.length + suffix.length > 120 && maxDesc > 1) {
      desc = `${desc.slice(0, maxDesc - 1)}…`;
    }

    lines.push(`${prefix}${desc}${suffix}`);
  }

  return `${lines.join("\n")}\n`;
}
