import { describe, expect, it } from "vitest";
import type { Rule, RuledocConfig } from "../types.js";
import { DEFAULT_CONFIG } from "../types.js";
import { generateContext } from "./context.js";

function makeRule(overrides: Partial<Rule> = {}): Rule {
  return {
    id: "",
    scope: "billing",
    subscope: "_general",
    fullScope: "billing",
    severity: "info",
    ticket: "",
    description: "test rule",
    file: "test.ts",
    line: 1,
    codeContext: "",
    title: "",
    rationale: "",
    owner: "",
    status: "",
    since: "",
    tags: [],
    links: [],
    supersededBy: "",
    dependsOn: [],
    conflictsWith: [],
    examples: [],
    testCases: [],
    ...overrides,
  };
}

function makeConfig(overrides: Partial<RuledocConfig> = {}): RuledocConfig {
  return { ...DEFAULT_CONFIG, ...overrides };
}

describe("generateContext", () => {
  it("produces header with active rule count, scope count, and date", () => {
    const rules = [makeRule(), makeRule({ scope: "auth", fullScope: "auth.session" })];
    const output = generateContext(rules, makeConfig());
    const lines = output.split("\n");

    expect(lines[0]).toBe("# Business Rules (auto-generated by ruledoc — do not edit)");
    expect(lines[1]).toMatch(/^# 2 active rules · 2 scopes · Generated \d{4}-\d{2}-\d{2}$/);
  });

  it("sorts by severity descending then fullScope alphabetically", () => {
    const rules = [
      makeRule({ fullScope: "billing.plans", severity: "info" }),
      makeRule({ fullScope: "auth.session", severity: "critical" }),
      makeRule({ fullScope: "auth.password", severity: "critical" }),
      makeRule({ fullScope: "notify.email", severity: "warning" }),
    ];
    const output = generateContext(rules, makeConfig());
    const ruleLines = output.split("\n").filter((l) => l.startsWith("["));

    expect(ruleLines[0]).toContain("[critical] auth.password:");
    expect(ruleLines[1]).toContain("[critical] auth.session:");
    expect(ruleLines[2]).toContain("[warning] notify.email:");
    expect(ruleLines[3]).toContain("[info] billing.plans:");
  });

  it("filters by context.severities", () => {
    const rules = [
      makeRule({ severity: "info", fullScope: "a" }),
      makeRule({ severity: "critical", fullScope: "b" }),
      makeRule({ severity: "warning", fullScope: "c" }),
    ];
    const config = makeConfig({ context: { severities: ["critical", "warning"] } });
    const output = generateContext(rules, config);
    const ruleLines = output.split("\n").filter((l) => l.startsWith("["));

    expect(ruleLines).toHaveLength(2);
    expect(ruleLines[0]).toContain("[critical]");
    expect(ruleLines[1]).toContain("[warning]");
  });

  it("truncates to maxRules", () => {
    const rules = Array.from({ length: 10 }, (_, i) => makeRule({ fullScope: `scope${i}`, description: `rule ${i}` }));
    const config = makeConfig({ context: { maxRules: 3 } });
    const output = generateContext(rules, config);
    const ruleLines = output.split("\n").filter((l) => l.startsWith("["));

    expect(ruleLines).toHaveLength(3);
  });

  it("truncates long descriptions to keep lines ≤ 120 chars", () => {
    const longDesc = "A".repeat(200);
    const rules = [makeRule({ description: longDesc })];
    const output = generateContext(rules, makeConfig());
    const ruleLines = output.split("\n").filter((l) => l.startsWith("["));

    expect(ruleLines[0].length).toBeLessThanOrEqual(120);
    expect(ruleLines[0]).toContain("…");
  });

  it("produces header only for empty rules", () => {
    const output = generateContext([], makeConfig());
    const lines = output.trimEnd().split("\n");

    expect(lines).toHaveLength(2);
    expect(lines[0]).toContain("Business Rules");
    expect(lines[1]).toContain("0 active rules · 0 scopes");
  });

  it("ends with trailing newline", () => {
    const output = generateContext([], makeConfig());
    expect(output.endsWith("\n")).toBe(true);
  });

  it("includes file and line in parentheses", () => {
    const rules = [makeRule({ file: "src/billing.ts", line: 42 })];
    const output = generateContext(rules, makeConfig());
    expect(output).toContain("(src/billing.ts:42)");
  });

  it("shows historical section for deprecated rules", () => {
    const rules = [
      makeRule({ status: "", description: "active rule" }),
      makeRule({ status: "deprecated", description: "old way", fullScope: "billing.old" }),
    ];
    const output = generateContext(rules, makeConfig());
    expect(output).toContain("# --- Historical ---");
    expect(output).toContain("[DEPRECATED]");
    expect(output).toContain("old way");
  });

  it("shows REMOVED tag for removed rules", () => {
    const rules = [makeRule({ status: "removed", description: "gone" })];
    const output = generateContext(rules, makeConfig());
    expect(output).toContain("[REMOVED]");
  });

  it("shows SUPERSEDED tag for supersededBy rules", () => {
    const rules = [makeRule({ supersededBy: "new-rule", description: "old rule" })];
    const output = generateContext(rules, makeConfig());
    expect(output).toContain("[SUPERSEDED by new-rule]");
  });

  it("shows historical count in header when historical rules exist", () => {
    const rules = [
      makeRule({ status: "", description: "active" }),
      makeRule({ status: "deprecated", description: "dep" }),
    ];
    const output = generateContext(rules, makeConfig());
    expect(output).toContain("1 historical");
  });

  it("does not show historical section when no historical rules", () => {
    const rules = [makeRule({ status: "" })];
    const output = generateContext(rules, makeConfig());
    expect(output).not.toContain("Historical");
  });

  it("includes title in rule line when present", () => {
    const rules = [makeRule({ title: "Plan Limit", description: "Free plan limited" })];
    const output = generateContext(rules, makeConfig());
    expect(output).toContain("Plan Limit");
  });

  it("excludes historical rules from active rules list", () => {
    const rules = [
      makeRule({ status: "", description: "active rule", fullScope: "billing" }),
      makeRule({ status: "deprecated", description: "old rule", fullScope: "billing.old" }),
    ];
    const output = generateContext(rules, makeConfig());
    // Active rule lines start with [severity], historical start with [DEPRECATED] etc.
    const ruleLines = output.split("\n").filter((l) => /^\[(?:info|warning|critical)\]/.test(l));
    expect(ruleLines).toHaveLength(1);
    expect(ruleLines[0]).toContain("active rule");
  });

  it("includes rule ID in output line when present", () => {
    const rules = [makeRule({ id: "RUL-001", fullScope: "billing", description: "ID rule" })];
    const output = generateContext(rules, makeConfig());
    expect(output).toContain("[info] RUL-001 billing:");
  });

  it("does not include ID part when id is empty", () => {
    const rules = [makeRule({ id: "", fullScope: "billing", description: "No ID" })];
    const output = generateContext(rules, makeConfig());
    expect(output).toContain("[info] billing:");
    expect(output).not.toContain("[info]  billing:");
  });

  it("sorts unknown severities after known ones", () => {
    const rules = [
      makeRule({ fullScope: "a", severity: "info" }),
      makeRule({ fullScope: "b", severity: "custom" }),
      makeRule({ fullScope: "c", severity: "other" }),
    ];
    const output = generateContext(rules, makeConfig());
    const ruleLines = output.split("\n").filter((l) => l.startsWith("["));

    expect(ruleLines[0]).toContain("[custom] b:");
    expect(ruleLines[1]).toContain("[other] c:");
    expect(ruleLines[2]).toContain("[info] a:");
  });
});
