import { buildTree, capitalize, sevBadge, splitByLifecycle } from "../tree.js";
import type { HistoryEntry, Rule, RuleWarning } from "../types.js";

export function generateMarkdown(rules: Rule[], warnings: RuleWarning[], history: HistoryEntry[] = []): string {
  const { active, historical } = splitByLifecycle(rules);
  const tree = buildTree(active);
  const scopes = Object.keys(tree).sort();
  const l: string[] = [];

  const histNote = historical.length > 0 ? ` · ${historical.length} historical` : "";
  l.push(
    "# Business Rules",
    "",
    "<!-- AUTO-GENERATED by ruledoc — do not edit -->",
    "",
    `> ${active.length} active rules · ${scopes.length} scopes · ${new Date().toISOString().split("T")[0]}${histNote}`,
    "",
  );

  // TOC
  l.push("## Table of contents", "");
  for (const s of scopes) {
    const subs = Object.keys(tree[s]).sort();
    const cnt = subs.reduce((n, sub) => n + tree[s][sub].length, 0);
    l.push(`- [**${capitalize(s)}**](#${s}) (${cnt})`);
    for (const sub of subs) {
      if (sub !== "_general") l.push(`  - [${capitalize(sub)}](#${s}${sub}) (${tree[s][sub].length})`);
    }
  }

  // Summary table
  l.push("", "## Summary", "");
  l.push("| Scope | Sub | Count | 🔴 | 🟡 |");
  l.push("|-------|-----|------:|---:|---:|");

  for (const s of scopes) {
    for (const sub of Object.keys(tree[s]).sort()) {
      const r = tree[s][sub];
      const cr = r.filter((x) => x.severity === "critical").length;
      const wr = r.filter((x) => x.severity === "warning").length;
      l.push(`| ${capitalize(s)} | ${capitalize(sub)} | ${r.length} | ${cr || "—"} | ${wr || "—"} |`);
    }
  }

  l.push("", "---", "");

  // Details
  for (const s of scopes) {
    const subs = Object.keys(tree[s]).sort();
    const all = subs.flatMap((sub) => tree[s][sub]);
    const cc = all.filter((r) => r.severity === "critical").length;

    l.push(`## ${capitalize(s)}`, "");
    if (cc) l.push(`> ⚠️ **${cc} critical rule${cc > 1 ? "s" : ""}**`, "");

    for (const sub of subs) {
      if (sub !== "_general") l.push(`### ${capitalize(sub)}`, "");

      for (const r of tree[s][sub]) {
        const tkt = r.ticket ? ` \`${r.ticket}\`` : "";
        const sv = r.severity !== "info" ? ` **[${r.severity}]**` : "";
        const idBadge = r.id ? `\`${r.id}\` ` : "";
        const anchor = r.id ? `<a id="rule-${r.id}"></a>` : "";
        l.push(`- ${anchor}${sevBadge(r.severity)}${sv} ${idBadge}${r.description}${tkt}`);
        if (r.title) l.push(`  <br>**${r.title}**`);
        if (r.rationale) l.push(`  <br>_${r.rationale}_`);
        if (r.owner) l.push(`  <br>Owner: \`${r.owner}\``);
        if (r.since) l.push(`  <br>Since: ${r.since}`);
        if (r.status) l.push(`  <br>Status: \`${r.status}\``);
        if (r.tags.length > 0) l.push(`  <br>Tags: ${r.tags.map(t => `\`${t}\``).join(", ")}`);
        if (r.supersededBy) l.push(`  <br>Superseded by: \`${r.supersededBy}\``);
        if (r.dependsOn.length > 0) l.push(`  <br>Depends on: ${r.dependsOn.map(d => `\`${d}\``).join(", ")}`);
        if (r.conflictsWith.length > 0) l.push(`  <br>Conflicts with: ${r.conflictsWith.map(c => `\`${c}\``).join(", ")}`);
        if (r.examples.length > 0) {
          l.push(`  <br>Examples:`);
          for (const ex of r.examples) l.push(`  - ${ex}`);
        }
        if (r.testCases.length > 0) l.push(`  <br>Tests: ${r.testCases.map(t => `\`${t}\``).join(", ")}`);
        if (r.links.length > 0) l.push(`  <br>Links: ${r.links.join(", ")}`);
        l.push(`  <br>📍 \`${r.file}:${r.line}\``);
        if (r.codeContext) l.push(`  <br>\`${r.codeContext}\``);
        l.push("");
      }
    }
    l.push("---", "");
  }

  // Historical Rules (deprecated/removed lifecycle)
  if (historical.length > 0) {
    l.push("## Historical Rules", "");
    for (const r of historical) {
      const tag = r.supersededBy ? `[SUPERSEDED by ${r.supersededBy}]` : r.status === "removed" ? "[REMOVED]" : "[DEPRECATED]";
      const histIdBadge = r.id ? `\`${r.id}\` ` : "";
      const histAnchor = r.id ? `<a id="rule-${r.id}"></a>` : "";
      l.push(`- ${histAnchor}~~${r.description}~~ ${tag} ${histIdBadge}\`${r.fullScope}\` · \`${r.severity}\``);
      if (r.title) l.push(`  <br>**${r.title}**`);
      if (r.rationale) l.push(`  <br>_${r.rationale}_`);
      l.push(`  <br>📍 \`${r.file}:${r.line}\``);
      l.push("");
    }
    l.push("---", "");
  }

  // Removed Rules (history)
  if (history.length > 0) {
    l.push("## Removed Rules", "");
    const recent = history.slice(Math.max(0, history.length - 20)).reverse();
    for (const entry of recent) {
      const date = entry.removedAt.split("T")[0];
      l.push(`- ~~${entry.rule.description}~~ \`${entry.rule.scope}\` · \`${entry.rule.severity}\` — removed ${date}`);
      l.push(`  <br>📍 \`${entry.rule.lastFile}:${entry.rule.lastLine}\``);
      if (entry.replacedBy) {
        l.push(`  <br>➡️ Replaced by [\`${entry.replacedBy}\`](#rule-${entry.replacedBy})`);
      }
      if (entry.acknowledged) {
        l.push(`  <br>✅ Acknowledged: \`${entry.acknowledged.ticket}\` — ${entry.acknowledged.reason}`);
      }
      l.push("");
    }
    l.push("---", "");
  }

  // Warnings
  if (warnings.length > 0) {
    l.push("## ⚠️ Warnings", "");
    l.push(`> ${warnings.length} issue${warnings.length > 1 ? "s" : ""} found during extraction`, "");
    for (const w of warnings) {
      l.push(`- \`${w.file}:${w.line}\` — ${w.message}`);
    }
    l.push("");
  }

  return l.join("\n");
}
