import { buildTree, capitalize, sevBadge } from "../tree.js";
import type { HistoryEntry, Rule, RuleWarning } from "../types.js";

export function generateMarkdown(rules: Rule[], warnings: RuleWarning[], _srcDir: string, history: HistoryEntry[] = []): string {
  const tree = buildTree(rules);
  const scopes = Object.keys(tree).sort();
  const l: string[] = [];

  l.push(
    "# Business Rules",
    "",
    "<!-- AUTO-GENERATED by ruledoc — do not edit -->",
    "",
    `> ${rules.length} rules · ${scopes.length} scopes · ${new Date().toISOString().split("T")[0]}`,
    "",
  );

  // TOC
  l.push("## Table of contents", "");
  for (const s of scopes) {
    const subs = Object.keys(tree[s]).sort();
    const cnt = subs.reduce((n, sub) => n + tree[s][sub].length, 0);
    l.push(`- [**${capitalize(s)}**](#${s}) (${cnt})`);
    for (const sub of subs) {
      if (sub !== "_general") l.push(`  - [${capitalize(sub)}](#${s}${sub}) (${tree[s][sub].length})`);
    }
  }

  // Summary table
  l.push("", "## Summary", "");
  l.push("| Scope | Sub | Count | 🔴 | 🟡 |");
  l.push("|-------|-----|------:|---:|---:|");

  for (const s of scopes) {
    for (const sub of Object.keys(tree[s]).sort()) {
      const r = tree[s][sub];
      const cr = r.filter((x) => x.severity === "critical").length;
      const wr = r.filter((x) => x.severity === "warning").length;
      l.push(`| ${capitalize(s)} | ${capitalize(sub)} | ${r.length} | ${cr || "—"} | ${wr || "—"} |`);
    }
  }

  l.push("", "---", "");

  // Details
  for (const s of scopes) {
    const subs = Object.keys(tree[s]).sort();
    const all = subs.flatMap((sub) => tree[s][sub]);
    const cc = all.filter((r) => r.severity === "critical").length;

    l.push(`## ${capitalize(s)}`, "");
    if (cc) l.push(`> ⚠️ **${cc} critical rule${cc > 1 ? "s" : ""}**`, "");

    for (const sub of subs) {
      if (sub !== "_general") l.push(`### ${capitalize(sub)}`, "");

      for (const r of tree[s][sub]) {
        const tkt = r.ticket ? ` \`${r.ticket}\`` : "";
        const sv = r.severity !== "info" ? ` **[${r.severity}]**` : "";
        l.push(`- ${sevBadge(r.severity)}${sv} ${r.description}${tkt}`);
        l.push(`  <br>📍 \`${r.file}:${r.line}\``);
        if (r.codeContext) l.push(`  <br>\`${r.codeContext}\``);
        l.push("");
      }
    }
    l.push("---", "");
  }

  // Removed Rules (history)
  if (history.length > 0) {
    l.push("## Removed Rules", "");
    const recent = [...history].reverse().slice(0, 20);
    for (const entry of recent) {
      const date = entry.removedAt.split("T")[0];
      l.push(`- ~~${entry.rule.description}~~ \`${entry.rule.scope}\` · \`${entry.rule.severity}\` — removed ${date}`);
      l.push(`  <br>📍 \`${entry.rule.lastFile}:${entry.rule.lastLine}\``);
      l.push("");
    }
    l.push("---", "");
  }

  // Warnings
  if (warnings.length > 0) {
    l.push("## ⚠️ Warnings", "");
    l.push(`> ${warnings.length} issue${warnings.length > 1 ? "s" : ""} found during extraction`, "");
    for (const w of warnings) {
      l.push(`- \`${w.file}:${w.line}\` — ${w.message}`);
    }
    l.push("");
  }

  return l.join("\n");
}
