export { ConfigError, resolveConfig } from "./config.js";
export { appendHistory, computeDiff, loadHistory, loadPreviousRules } from "./diff.js";
export { generateHTML } from "./output/html.js";
export { generateJSON } from "./output/json.js";
export { generateMarkdown } from "./output/markdown.js";
export type { ExtractionResult } from "./parser.js";
export { extractRules } from "./parser.js";
export type { ProtectionResult } from "./protect.js";
export { checkProtection } from "./protect.js";
export { buildTree } from "./tree.js";
export type { HistoryEntry, Rule, RuleDiff, RuledocConfig, RuleRemoval, RuleWarning, ScopeTree } from "./types.js";
export { buildPattern, DEFAULT_CONFIG, DEFAULT_SEVERITIES } from "./types.js";
